### ISSUE TITLE
Windows and Linux Builds

### ISSUE THREAD

**Issue by tracker1** [fresk-nc/VOX#1]
Would you be open to help getting this to work with Windows and Linux?

**Comment by fresk-nc** [comment]
Sure! :)

**Comment by fresk-nc** [comment]
Done.

**Comment by tracker1** [comment]
Awesome, thanks... I'd been considering setting up Jenkins in windows on a cheap VPS so that I can do windows targeted builds for a couple projects myself.

May I ask, What's your solution on this?  Are you doing builds by hand?  Do you have it automated?
