### ISSUE TITLE
Cannot run app with `npm  run`

### ISSUE THREAD

**Issue by ssi-anik** [fresk-nc/VOX#2]
This [solution](https://github.com/shama/stylus-loader/issues/115#issuecomment-265407408) fixed the build errors attached below but nothing loads up.

![Build error](https://user-images.githubusercontent.com/2676602/54232833-ce67c080-4535-11e9-81b1-b260ca7ffcd6.png)
![image](https://user-images.githubusercontent.com/2676602/54232946-11c22f00-4536-11e9-9dc7-0ed43e6a9ef3.png)

**Comment by fresk-nc** [comment]
Thank you for the issue. 
I did
```
npm i -D stylus@0.54.5
npm i -D stylus-loader@3.0.2
```
and it works fine. Can you try again? I use nodejs v8.9.0

**Comment by ssi-anik** [comment]
With node 8.11, it runs well. when I use node 10.15 it shows nothing. Anyway, good initiative. 
![image](https://user-images.githubusercontent.com/2676602/54372464-91224080-46a5-11e9-8da5-1f6921c23c82.png)
